### ISSUE TITLE
WARNING: falco-cli 0.22.3 does not provide the extra 'just'

### ISSUE THREAD

**Issue by wilecoyote1** [Tobi-De/falco#101]
on windows 10, powershell 7.44

when i launch the command 

pip install --upgrade "falco-cli[just]" 

i've got

WARNING: falco-cli 0.22.3 does not provide the extra 'just'

after that, the command 

just

return 

just: The term 'just' is not recognized as a name of a cmdlet, function, script file, or executable program.

**Comment by Tobi-De** [comment]
Oh yes, the project from which I'm installing just ([this one](https://github.com/justin-yan/pybin)) does not support Windows. I should have mentioned that in the README. You'll need to install `just` manually. You can get it with Chocolatey or Winget:

https://just.systems/man/en/chapter_4.html

```shell
choco install just
winget install --id Casey.Just --exact
```
