### ISSUE TITLE
Windows : error launch just install-hatch

### ISSUE THREAD

**Issue by wilecoyote1** [Tobi-De/falco#102]
on Windows 10, on Powershell 7.44

finaly, i install just directly with the binaries of just

when i launch the command just install-hatch, i'v got

error: Recipe `install-hatch` could not be run because just could not find the shell: program not found

**Comment by Tobi-De** [comment]
> error: Recipe install-hatch could not be run because just could not find the shell: program not found

😅 My bad again on this one. I think I'll just remove this recipe (just command). The install script is only meant for Linux and macOS (not even sure about macOS).

https://hatch.pypa.io/latest/install/#installers
