### ISSUE TITLE
delete modal for crud views

### ISSUE THREAD

**Issue by Tobi-De** [Tobi-De/falco#17]
The current delete button generated with `crud` command use the default browser confirm, but it might be a good idea to use the native modal for a custom UI

- https://htmx.org/examples/confirm/
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

**Comment by 786raees** [comment]
@Tobi-De can you please explain it in more details because I don't want to repeat the last incident.

**Comment by Tobi-De** [comment]
> @Tobi-De can you please explain it in more details because I don't want to repeat the last incident.

I'm not even sure this feature is really worth it, have you tried the `crud` command, or run the demo project locally? try one of those options beforehand, it will make the explanation simpler.

**Comment by 786raees** [comment]
After thoroughly executing all the presently available commands, I must express my dissatisfaction with the method by which the pre-commit hook has been implemented. Ideally, upon project initialization, all tests, lintings, and formatting procedures should operate without a hitch. However, I have encountered a significant issue. Subsequent to the incorporation of the pre-commit hook -- post project initialization -- and upon the creation of a commit, I am confronted with a plethora of errors. This suggests that the integration may not be functioning as smoothly as anticipated, potentially leading to a disruption in the development workflow.

**Comment by Tobi-De** [comment]
> After thoroughly executing all the presently available commands, I must express my dissatisfaction with the method by which the pre-commit hook has been implemented. Ideally, upon project initialization, all tests, lintings, and formatting procedures should operate without a hitch. However, I have encountered a significant issue. Subsequent to the incorporation of the pre-commit hook -- post project initialization -- and upon the creation of a commit, I am confronted with a plethora of errors. This suggests that the integration may not be functioning as smoothly as anticipated, potentially leading to a disruption in the development workflow.

sorry for that @786raees , you are right, I completely forgot and left the pre-commit config in a broken state, I just made a new release, can you try it and tell me how it goes? I think at worst you'll just get html files to format.

**Comment by 786raees** [comment]
@Tobi-De that are working beautifully now but when I push the code it fails on GitHub can you please check that one too.

**Comment by Tobi-De** [comment]
> @Tobi-De that are working beautifully now but when I push the code it fails on GitHub can you please check that one too.

Can yo show the error you are getting?
Are you still talking about a generated project or the falco project itself? 
If you are talking about falco pre-commit then make sure you have the latest changes, should be fixed too

**Comment by 786raees** [comment]
![image](https://github.com/Tobi-De/falco/assets/96701299/de750f01-bae5-4a75-aa88-9f16d761a0cd)

**Comment by Tobi-De** [comment]
This is not a priority for now
