### ISSUE TITLE
New command reset-migrations

### ISSUE THREAD

**Issue by Tobi-De** [Tobi-De/falco#18]
I think I've come across a potential addition: a new command, `falco reset-migrations`.

1. Firstly, it run `falco rm-migrations`.
2. Then, it clears your Django migrations table:

    ```python
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM django_migrations")
    ```

3. and `python manage.py makemigrations`
4. Lastly, it executes `python manage.py migrate --fake` to ensure the new migrations are added to the migrations table as if they were already applied

This approach allows you to retain your data while achieving a clean slate for migrations. What are your thoughts on this @hammadarshad1 ?

_Originally posted by @Tobi-De in https://github.com/Tobi-De/falco/issues/12#issuecomment-1867385038_

**Comment by hammadarshad1** [comment]
Good idea—I believe it's a good starting point. One quick suggestion: let's avoid adding `makemigration` command here, as this might generate new migration files and have a chance to apply those changes as `--fake`.

**Comment by Tobi-De** [comment]
> Good idea—I believe it's a good starting point. One quick suggestion: let's avoid adding `makemigration` command here, as this might generate new migration files and have a chance to apply those changes as `--fake`.

Here's a revised version:

I'm not sure I'm understanding this, are you suggesting leaving step 3 and 4 to the user?
The issue I see here is that the user may not have their current migrations in sync with the database. For example, if they intend to reset migrations but overlook the recent addition of a new field, forgetting to create and apply the corresponding migration, and then proceed with the migration reset.
 
In such a scenario, if we delete old migrations, make new ones and apply them as fake, their database might lack a field that their table migrations specify. Is that the issue you are highlighting here?
  
 If so, I believe a straightforward reminder in the documentation or during command execution (possibly a code check) to ensure all current migrations are applied before running the command could suffice.
 Without steps 3 and 4 , the command becomes essentially useless, leaving the user with the only option to reset the database completely.

**Comment by hammadarshad1** [comment]
No, I mean avoid the 3rd step ‘makemigrations’ from the pipeline, as clearly we are not deleting anything from db other than migration table data. In case of running makemigration command, if there is a new migration file generated, then this newly generated migration will be applied as fake in the next step. Means Django will also mark this new migration as applied and will not make any db changes. Wdyt?

**Comment by Tobi-De** [comment]
If we don't run the makemigrations step, the only migrations that would be applied as fake are the native django ones, for the use tables, sessions, etc... :thinking: 
Let's say we do that, what would be the next step for the user ? he has not migrations, but likely has his own apps (products, carts, etc..), in this case, the migrations for those apps were deleted, so his need to create new ones, he proceed to run `makemigrations`, the migration tables being reset, for all his apps, the count will start at 0001, if he then tries to apply those migrations, he will then get and error telling him that the tables for the models in products, carts, whatever, already exists, if he want to keep his data, he has to run the `fake` migrate command, so essentially the logical step for the user will be to run step 3 and 4 again, that's why I think it's necessary to run the `makemigrations` command, he will eventually has to do so himself and then run `migration --fake` again.
I'm I missing something here ?

**Comment by Tobi-De** [comment]
@all-contributors please add @hammadarshad1  for :thinking:

**Comment by Tobi-De** [comment]
@all-contributors please add @hammadarshad1  for ideas
