### ISSUE TITLE
install-crud-utils should make the core folder a package if it does not exists

### ISSUE THREAD

**Issue by Tobi-De** [Tobi-De/falco#21]
the start-project template no longer comes with the core app

**Comment by hammadarshad1** [comment]
Can you explain a bit more about it? I want to pick this one as my initial patch.

**Comment by Tobi-De** [comment]
Hi @hammadarshad1, actually, I've already done this one; I forgot to close the issue. The problem was that when I installed the CRUD utils, I did it in a `core/utils.py` file. If this folder did not exist, I created it, but previously, I did not add the `__init__.py` file in the folder to mark it as a package, now I do.
If your are looking for something to work on, there is this https://github.com/Tobi-De/falco/issues/22 and ti's quite simple

**Comment by hammadarshad1** [comment]
> Hi @hammadarshad1, actually, I've already done this one; I forgot to close the issue. The problem was that when I installed the CRUD utils, I did it in a `core/utils.py` file. If this folder did not exist, I created it, but previously, I did not add the `__init__.py` file in the folder to mark it as a package, now I do. If your are looking for something to work on, there is this #22 and ti's quite simple

Gotcha! Thank you for mentioning the opened issue. I will pick this one and come up with the patch.
