### ISSUE TITLE
try to download the latest version of htmx during startproject

### ISSUE THREAD

**Issue by Tobi-De** [Tobi-De/falco#22]
The starter project comes with an htmx js file already. The idea is, after initializing the project, try to download and install the latest version using `falco htmx`. This way, in case there is a new version, the user always starts with the latest htmx version. This step is optional, so it should fails silently in case of a network error, for example.

**Comment by 786raees** [comment]
@Tobi-De can you please explain this because when I see the code I think you are already doing this?

**Comment by 786raees** [comment]
> @Tobi-De can you please explain this because when I see the code I think you are already doing this?

Would you like to allow developers to update the **HTMX** version in their project simply by using the command `falco htmx update` after they've set up the project?

**Comment by Tobi-De** [comment]
> @Tobi-De can you please explain this because when I see the code I think you are already doing this?

Hi @786raees , nope the current code does not do this
The `start-project` currently uses Django's `startproject` to generate a new project with the included project blueprint, and that blueprint already includes an `htmx.js`. Since this file comes with the blueprint, it might not always be the latest available version of htmx, so the idea is:
- There should be some kind of `update_htmx` method that runs after the [init_project](https://github.com/Tobi-De/falco/blob/main/src/falco/commands/start_project.py#L108) function.
- This method will execute `falco htmx` or import and run the class similar to how the `reset-migration` command runs the `rm-migrations` [here](https://github.com/Tobi-De/falco/blob/main/src/falco/commands/reset_migrations.py#L49).
- If there is any kind of error, the function will fail silently, meaning it won't report any errors to the user so that `start-project` does not depend on the network.
- If the command is successful, it will override the existing file in `static/vendors/htmx.js` with the newly downloaded file.

**Comment by Tobi-De** [comment]
> > @Tobi-De can you please explain this because when I see the code I think you are already doing this?
> 
> Would you like to allow developers to update the **HTMX** version in their project simply by using the command `falco htmx update` after they've set up the project?

Hum..., interesting that would be basically equivalent to `falco htmx -o <project_name>/static/vendors/htmx.js`, maybe a new script to add [here](https://github.com/Tobi-De/falco/blob/main/src/falco_blueprints/project_name/pyproject.toml#L48) but I don't think it is worth adding code for that.

**Comment by 786raees** [comment]
@Tobi-De really sorry to bother you but can you please guide me on how can I test my code on local?

**Comment by Tobi-De** [comment]
> @Tobi-De really sorry to bother you but can you please guide me on how can I test my code on local?

No worries :), what have you used to setup the project ? hatch ?

**Comment by 786raees** [comment]
> > @Tobi-De really sorry to bother you but can you please guide me on how can I test my code on local?
> 
> No worries :), what have you used to setup the project ? hatch ?

yes

**Comment by Tobi-De** [comment]
If you want want to run the test suite, then simply run `hatch run pytest`, if you want to run tests only for the `start-project` command then run `hatch run pytest tests/commands/test_start_project.py`.

If you want to see if you change are working, the simplest way (and that's what I've being doing) is just to run `falco start-project whatever_name` in a hatch shell to see if it works as expected, there is not special setup for that, just try the command directly to see if it does what you expect, if yes, and everything is working, delete the created project, commit and make a pull request.

Have I answered your question ?
