### ISSUE TITLE
start-app command fails with an error

### ISSUE THREAD

**Issue by kamon** [Tobi-De/falco#90]
Hi,
I followed the documentation and made sure falco-cli (and hatch) are installed in a Python 3.12 virtual env.
Then:
* `falco start-project myjourney && cd myjourney`
* `hatch shell`
* `hatch run python manage.py migrate`

Next step, I try to create the "entries" app:
`falco start-app entries`

I get the following weird error:
```
Error: Traceback (most recent call last):
  File "/Users/ka/DEV/DJANGO/FALCO/myjourney/manage.py", line 10, in main
    from django.core.management import (  # pylint: disable=import-outside-toplevel
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ka/DEV/DJANGO/FALCO/myjourney/manage.py", line 23, in <module>
    main()
  File "/Users/ka/DEV/DJANGO/FALCO/myjourney/manage.py", line 14, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH 
environment variable? Did you forget to activate a virtual environment?
```
Also, an empty "entries" subfolder has been created.

This issue seems related to the interaction between falco and hatch, but I am not sure.
Any ideas?

Thanks!

**Comment by kamon** [comment]
Yes, it worked as you said.
After opening a new terminal, and running `hatch shell` I got switched to the virtual env provided by hatch, and then the start-app command worked as expected.
Many thanks!

**Comment by Tobi-De** [comment]
> Yes, it worked as you said. After opening a new terminal, and running `hatch shell` I got switched to the virtual env provided by hatch, and then the start-app command worked as expected. Many thanks!

You're welcome, sometimes it's just the terminal messing with you :)
