### ISSUE TITLE
the latest version of hatch breaks hatch-pip-compile

### ISSUE THREAD

**Issue by Tobi-De** [Tobi-De/falco#91]
https://github.com/pypa/hatch/issues/1468
https://github.com/juftin/hatch-pip-compile/pull/80

The simplest solution for now is that when an error occur because of this, run `hatch env prune` to delete all environnement and then`hatch env create` to recreate the default environnment

**Comment by juftin** [comment]
Alright, this should be resolved in [hatch-pip-compile 1.11.2](https://github.com/juftin/hatch-pip-compile/releases/tag/v1.11.2). The fix for this was very easy, but frustratingly involved re-writing a good part of my test suite.
