### ISSUE TITLE
if admin exists, ignore it

### ISSUE THREAD

**Issue by Tobi-De** [Tobi-De/falco#96]
The error below  is raised when running crud and an admin is already registered for the targeted model(s)

```shell
django.contrib.admin.sites.AlreadyRegistered
```
I'm not sure how, but the idea is to check if an admin already exists for the model, and if it does, skip the admin generation step. The function responsible for this also handles generating admins for all models when no model_name is specified. I think the simplest solution here is to check if the admin file exists and is not empty. If the file is not empty, it would be complicated to handle all possible scenarios (e.g., one model has an admin in the app, but another does not). Therefore, we should do nothing and perhaps print a warning.

This is the code that needs to change https://github.com/Tobi-De/falco/blob/main/src/falco/commands/crud/model_crud.py#L440

**Comment by earthcomfy** [comment]
Hi, can I work on this? I can include a check before attempting to register the model

**Comment by Tobi-De** [comment]
> Hi, can I work on this? I can include a check before attempting to register the model

Absolutely :)

**Comment by Tobi-De** [comment]
> Hey, yes thanks for updating the description. Wouldn't something like this suffice
> 
> ```python
> existing_code = admin_file.read_text()
> 
> # Avoid adding duplicate registrations if model_name is already registered
> if model_name and f"admin_site.register({model_name}" in existing_code:
>     rich_print(f"Model {model_name} is already registered.")
>     return admin_file
> ```
> 

`f"admin_site.register({model_name}"` this is not the only way to register an admin, this `admin.register(Model)` is also an option. Maybe just checking for `{model_name.title()}Admin` is enought

> if model_name is not provided, we can assume it is for all models during initial setup (?)

Nope, the crud command could be run on an existing project with an existing admin file (this is what lead me to discover the issue in the first place), not only during initial setup, I think the simplest solution is just to skip the step if the admin is generated for all models (no model_name provided) and the admin file exists and is not empty

**Comment by Tobi-De** [comment]
@all-contributors please add @earthcomfy  for code
